version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/devops-k8s-demo
      - aws ecr get-login-password | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo Building Docker image
      - docker build -t $REPOSITORY_URI:latest .

  post_build:
    commands:
      - echo Pushing Docker image
      - docker push $REPOSITORY_URI:latest
      - echo Build completed